### ISSUE TITLE
Fix build on i386

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#989]
```
[ 69%] Building CXX object src/CMakeFiles/tarantool.dir/main.cc.o
cd /wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/src && /usr/local/libexec/ccache/g++48   -DCORO_ASM -DNDEBUG -DNVALGRIND -D__STDC_CONSTANT_MACROS=1 -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -O2 -pipe -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -Wl,-rpath=/usr/local/lib/gcc48 -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -std=c++11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -Wno-invalid-offsetof -I/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/src -I/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/src/lib -I/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src -I/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/third_party/luajit/src -I/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/third_party -I/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/third_party/coro -I/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/third_party/gopt    -o CMakeFiles/tarantool.dir/main.cc.o -c /wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/src/main.cc
Linking CXX executable tarantool
cd /wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src/src && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/tarantool.dir/link.txt --verbose=1
/usr/local/libexec/ccache/g++48   -O2 -pipe -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -Wl,-rpath=/usr/local/lib/gcc48 -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -std=c++11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -Wno-invalid-offsetof   -Wl,-rpath=/usr/local/lib/gcc48 -L/usr/local/lib/gcc48 -rdynamic CMakeFiles/tarantool.dir/main.cc.o  -o tarantool  box/libbox.a libserver.a libcore.a ../libmisc.a lib/bitset/libbitset.a lib/libmsgpuck.a ../libeio.a ../libgopt.a ../libcjson.a ../libyaml.a -lreadline -ltermcap ../third_party/luajit/src/libluajit.a /usr/local/lib/libintl.so ../third_party/sophia/libsophia.a lib/salad/libsalad.a lib/small/libsmall.a -lpthread ../libev.a -lm ../libcoro.a lib/bit/libbit.a -Wl,-rpath,/usr/local/lib:
lib/small/libsmall.a(slab_arena.c.o): In function `slab_map':
slab_arena.c:(.text+0x324): undefined reference to `__sync_val_compare_and_swap_8'
collect2: error: ld returned 1 exit status
src/CMakeFiles/tarantool.dir/build.make:108: recipe for target 'src/tarantool' failed
gmake[2]: *** [src/tarantool] Error 1
gmake[2]: Leaving directory '/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src'
CMakeFiles/Makefile2:628: recipe for target 'src/CMakeFiles/tarantool.dir/all' failed
gmake[1]: *** [src/CMakeFiles/tarantool.dir/all] Error 2
gmake[1]: Leaving directory '/wrkdirs/usr/ports/databases/tarantool/work/tarantool-1.6.5-305-g3a9640b-src'
Makefile:139: recipe for target 'all' failed
gmake: *** [all] Error 2
*** [do-build] Error code 1
```
Fallow this https://gcc.gnu.org/bugzilla/show_bug.cgi?id=34115

```
--- cmake/compiler.cmake.orig	2015-08-22 18:47:17 UTC
+++ cmake/compiler.cmake
@@ -129,6 +129,10 @@ macro(enable_tnt_compile_flags)
     if (CMAKE_COMPILER_IS_GNUCC)
         # A workaround for Redhat Developer Toolset 2.x on RHEL/CentOS 5.x
         add_compile_flags("C" "-fno-gnu89-inline")
+        if (NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
+            add_compile_flags("C;CXX"
+	        "-march=i686")
+        endif()
     endif()

     add_definitions("-D__STDC_FORMAT_MACROS=1")
```

**Comment by kostja** [comment]
@mejedi, please review and accet the patch if it's correct.

**Comment by mejedi** [comment]
Current master builds on i386 with gcc4.6 just fine. And so does 1.6

**Comment by mejedi** [comment]
It looks like we are compiling with SSE2 by default (simd.cmake).
