### PR TITLE
Fix build with OpenSSL 3.0

### LINKED ISSUE #6477: Upgrade openssl from 1.1 to 3
The new version of OpenSSL was released. See [this](https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/)

If we are using the current tarantool with OpenSSL@3 there are a lot of deprecation warnings like:

```
/Users/tntmac08.tarantool.i/v.ioffe/tarantool/src/lib/crypto/crypto.c:378:9: error: 'HMAC_CTX_new' is deprecated [-Werror,-Wdeprecated-declarations]
        return HMAC_CTX_new();
               ^
/opt/homebrew/opt/openssl@3/include/openssl/hmac.h:33:1: note: 'HMAC_CTX_new' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 HMAC_CTX *HMAC_CTX_new(void);
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
```

and tests couldn't be passed, e.g.:

```
004] app/crypto.test.lua                                             [ fail ]
[004] 
[004] Test failed! Result content mismatch:
[004] --- app/crypto.result	Tue Sep 28 10:40:42 2021
[004] +++ var/rejects/app/crypto.reject	Tue Sep 28 17:04:56 2021
[004] @@ -167,13 +167,11 @@
[004]  ...
[004]  ciph.decrypt(enc, bad_pass, iv)
[004]  ---
[004] -- error: 'OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad
[004] -    decrypt'
[004] +- error: 'OpenSSL error: error:1C800064:Provider routines::bad decrypt'
[004]  ...
[004]  ciph.decrypt(enc, pass, bad_iv)
[004]  ---
[004] -- error: 'OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad
[004] -    decrypt'
[004] +- error: 'OpenSSL error: error:1C800064:Provider routines::bad decrypt'
[004]  ...
[004]  test_run:cmd("clear filter")
[004]  ---

```

Have to upgrade OpenSSL from 1.1 to 3: fix all warnings and fix tests if needed. Also, fix CI, where openssl@1.1 is hardcoded.

### PR DESCRIPTION
**Pull request by locker**
Two things we need to do to fix build with OpenSSL 3.0:
1. Use `EVP_MAC_*` functions instead of `HMAC_*`:
   https://www.openssl.org/docs/man3.0/man3/HMAC_CTX_new.html
2. Load the Legacy provider to enable legacy algorithms, such as MD4
   https://wiki.openssl.org/index.php/OpenSSL_3.0#Programming_in_OpenSSL_3.0

Closes #6477

### CODE REVIEW

File: rpm/tarantool.spec [hunk 1]
```diff
@@ -35,14 +35,7 @@ BuildRequires: gcc-c++ >= 4.5
 BuildRequires: coreutils
```
Comment (Totktonada) [inline rpm/tarantool.spec:35]: It seems, we should also revert 33830978870bbe8cdc3c23fa06ba0f141a960124.

File: src/lib/crypto/crypto.c [hunk 2]
```diff
@@ -406,22 +421,46 @@ crypto_EVP_get_digestbyname(const char *name)
...
+#if OPENSSL_VERSION_NUMBER < 0x30000000L
+	(void)digest;
 	return HMAC_Init_ex(ctx, key, len, md, impl);
+#else
+	(void)md;
+	(void)impl;
+	OSSL_PARAM params[2];
+	params[0] = OSSL_PARAM_construct_utf8_string("digest",
+						     (char *)digest, 0);
+	params[1] = OSSL_PARAM_construct_end();
```
Comment (Totktonada) [inline src/lib/crypto/crypto.c:436]: 1. Shouldn't we use `OSSL_PARAM_set_octet_string()`? We can pass any binary data from Lua here.
2. What if I'll pass data with zero in the middle?

Comment (Totktonada) [reply src/lib/crypto/crypto.c:436]: I misinterpreted a purpose of `digest` argument. Now I got it, it is "md5", "sha1" and so on. Sorry for noise.

File: src/lua/crypto.lua [hunk 3]
```diff
@@ -28,10 +28,11 @@ ffi.cdef[[
     HMAC_CTX *crypto_HMAC_CTX_new(void);
```
Comment (Totktonada) [inline src/lua/crypto.lua:28]: Nit: Maybe change `HMAC_CTX` here to `crypto_HMAC_CTX` for the parity with the C code?

File: rpm/tarantool.spec (hunk 1 above)
Comment (locker) [reply rpm/tarantool.spec:35]: Looks okay. Done. Thanks!

File: src/lua/crypto.lua (hunk 3 above)
Comment (Totktonada) [reply src/lua/crypto.lua:28]: Okay.

**Review by Totktonada — APPROVED** [review]
LGTM.

I can't thoroughly validate the changes against correctness of the openssl API usage (has no experience there), but visually I don't see problems.

**Comment by locker** [comment]
Cherry-picked to 2.10.
