### ISSUE TITLE
Error: tarantool 1.6 did not build on OS X: 10.9.4

### ISSUE THREAD

**Issue by ingeniarius** [tarantool/tarantool#442]
Can't build via:

brew install https://raw.githubusercontent.com/tarantool/tarantool/master/extra/tarantool.rb

HEAD at 033ed69

```
Generating third_party/sophia/env/libsophia.a
cc -g -O0 -std=c99 -pedantic -Wextra -Wall -c rt/sr_crc.c
In file included from rt/sr_crc.c:18:
In file included from rt/libsr.h:35:
rt/sr_spinlock.h:12:9: error: unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
typedef pthread_spinlock_t srspinlock;
        ^~~~~~~~~~~~~~~~~~
        pthread_rwlock_t
/usr/include/sys/_types/_pthread_rwlock_t.h:30:35: note: 'pthread_rwlock_t' declared here
typedef __darwin_pthread_rwlock_t       pthread_rwlock_t;
                                        ^
In file included from rt/sr_crc.c:18:
In file included from rt/libsr.h:35:
rt/sr_spinlock.h:16:2: warning: implicit declaration of function 'pthread_spin_init' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_spin_init(l, 0);
        ^
rt/sr_spinlock.h:21:2: warning: implicit declaration of function 'pthread_spin_destroy' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_spin_destroy(l);
        ^
rt/sr_spinlock.h:26:2: warning: implicit declaration of function 'pthread_spin_lock' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_spin_lock(l);
        ^
rt/sr_spinlock.h:31:2: warning: implicit declaration of function 'pthread_spin_unlock' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_spin_unlock(l);
        ^
4 warnings and 1 error generated.
make[3]: *** [rt/sr_crc.o] Error 1
make[2]: *** [third_party/sophia/env/libsophia.a] Error 2
make[1]: *** [CMakeFiles/libsophia.dir/all] Error 2
```
