### ISSUE TITLE
Compiling tarantool with Address Sanitizer 

### ISSUE THREAD

**Issue by SivaDotRender** [tarantool/tarantool#2050]
I am having difficulties compiling tarantool with Address Sanitizer (which was added to the project in commit afd229393ecba61ce39e9c302fe3e7e7e0afa8c8). More specifically, I am getting this error:

```
/home/tarantool/src/fiber.c:123:2: error: implicit declaration of function '__sanitizer_start_switch_fiber' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ASAN_START_SWITCH_FIBER(asan_state, 1,
```

What is cause of this issue?

**Comment by bigbes** [comment]
Are you using Clang with version >=3.9?

**Comment by rtsisyk** [comment]
@SivaDotRender please install clang 3.9 from http://apt.llvm.org/

**Comment by SivaDotRender** [comment]
I am getting the game error with clang 3.9

```
$ which clang
/home/clang/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang
$ clang --version
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/clang/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin
```

**Comment by rtsisyk** [comment]
@SivaDotRender you also need the latest llvm development files (heades, libraries and so on) in the system. Anyway, I'll try to reproduce your problem on Ubuntu 14.04.

**Comment by rtsisyk** [comment]
Please feel free to contact us on [Telegram Channel](http://telegram.me/tarantool) if you  have questions about Tarantool development.

**Comment by bigbes** [comment]
Looks, like you're trying to build with clang 3.9 with older header files (that were installed before).

**Comment by SivaDotRender** [comment]
@bigbes you are correct. That solved my issue.
