### PR TITLE
github-ci: use openssl@1.1

### LINKED ISSUE #6468: openssl not found
OSX workflows use different versions of OpenSSL.

There is OpenSSL on tntmac machines, but that openssl has a 1.1 version
```
tntmac07.tarantool.i@tntmac07 ~ % which openssl
/opt/homebrew/opt/openssl@1.1/bin/openssl
```

Brew now provides new OpenSSL 3.0. So, it makes conflicts and builds couldn't find openssl packages.
So, it raises 
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:396 (message):
  Could NOT find OpenSSL development files (libssl-dev/openssl-devel package)

```

### PR DESCRIPTION
**Pull request by VitaliyaIoffe**
OSX workflows use brew for install openssl.
There was a new release of openssl@3.0 and
homebrew updated the openssl formula.

Close #6468

### CODE REVIEW

**Comment by Totktonada** [comment]
> OpenSSL 3.0 is a major release and not fully backwards compatible with the previous release. Most applications that worked with OpenSSL 1.1.1 will still work unchanged and will simply need to be recompiled (although you may see numerous compilation warnings about using deprecated APIs). Some applications may need to make changes to compile and work correctly, and many applications will need to be changed to avoid the deprecations warnings.

https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/

Did you try to compile against openssl 3.0?

**Comment by VitaliyaIoffe** [comment]
> Did you try to compile against OpenSSL 3.0?

We have deprecated errors during the building, therefore, we in case:

> many applications will need to be changed to avoid the deprecations warnings.


See below.

```
/Users/tntmac08.tarantool.i/v.ioffe/tarantool/src/lib/crypto/crypto.c:378:9: error: 'HMAC_CTX_new' is deprecated [-Werror,-Wdeprecated-declarations]
        return HMAC_CTX_new();
               ^
/opt/homebrew/opt/openssl@3/include/openssl/hmac.h:33:1: note: 'HMAC_CTX_new' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 HMAC_CTX *HMAC_CTX_new(void);
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/Users/tntmac08.tarantool.i/v.ioffe/tarantool/src/lib/crypto/crypto.c:390:2: error: 'HMAC_CTX_free' is deprecated [-Werror,-Wdeprecated-declarations]
        HMAC_CTX_free(ctx);
        ^
/opt/homebrew/opt/openssl@3/include/openssl/hmac.h:35:1: note: 'HMAC_CTX_free' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 void HMAC_CTX_free(HMAC_CTX *ctx);
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/Users/tntmac08.tarantool.i/v.ioffe/tarantool/src/lib/crypto/crypto.c:433:9: error: 'HMAC_Init_ex' is deprecated [-Werror,-Wdeprecated-declarations]
        return HMAC_Init_ex(ctx, key, len, md, impl);
               ^
/opt/homebrew/opt/openssl@3/include/openssl/hmac.h:43:1: note: 'HMAC_Init_ex' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/Users/tntmac08.tarantool.i/v.ioffe/tarantool/src/lib/crypto/crypto.c:439:9: error: 'HMAC_Update' is deprecated [-Werror,-Wdeprecated-declarations]
        return HMAC_Update(ctx, data, len);
               ^
/opt/homebrew/opt/openssl@3/include/openssl/hmac.h:45:1: note: 'HMAC_Update' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int HMAC_Update(HMAC_CTX *ctx, const unsigned char *data,
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/Users/tntmac08.tarantool.i/v.ioffe/tarantool/src/lib/crypto/crypto.c:445:9: error: 'HMAC_Final' is deprecated [-Werror,-Wdeprecated-declarations]
        return HMAC_Final(ctx, md, len);
               ^
/opt/homebrew/opt/openssl@3/include/openssl/hmac.h:47:1: note: 'HMAC_Final' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int HMAC_Final(HMAC_CTX *ctx, unsigned char *md,
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
5 errors generated.
make[3]: *** [src/lib/crypto/CMakeFiles/crypto.dir/crypto.c.o] Error 1
make[2]: *** [src/lib/crypto/CMakeFiles/crypto.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

Do we want to resolve it now? Or upgrade to the new version as a part of a new ticket?

**Review by tsafin — APPROVED** [review]
Agreed that we need to fix current breakage with macos/arm targets ASAP, postponing deal with upgrade to openssl@3.0 for another ticket. (Upgrade between major OpenSSL versions is usually very painful, as they tend to break ABI in this case)

**Comment by Totktonada** [comment]
Something except deprecation warnings (we can temporary disable them with `-Wno-deprecated`)?

**Comment by tsafin** [comment]
> Something except deprecation warnings (we can temporary disable them with `-Wno-deprecated`)?

At the times of migration from 1.0 to 1.1 true resolution of such multiple deprecation warnings meant massive rework of SSL customer code. (Though, at the moment, there might be not simple deprecation, but rather direct ABI breakage)

In any case, even if migration is simple, it looks as worth separate ticket which should be handled separately (as it might require not only cmake define changes). I still vote for the current simple workaround - we need to make master green asap.

**Comment by Totktonada** [comment]
If you want my opinion, I'm waiting for an answer to my question.

**Comment by VitaliyaIoffe** [comment]
I tried to use OpenSSL3 and it failed a lot of test-run's suites. For, instance:
```
[004] app/crypto.test.lua                                             [ fail ]
[004] 
[004] Test failed! Result content mismatch:
[004] --- app/crypto.result	Tue Sep 28 10:40:42 2021
[004] +++ var/rejects/app/crypto.reject	Tue Sep 28 17:04:56 2021
[004] @@ -167,13 +167,11 @@
[004]  ...
[004]  ciph.decrypt(enc, bad_pass, iv)
[004]  ---
[004] -- error: 'OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad
[004] -    decrypt'
[004] +- error: 'OpenSSL error: error:1C800064:Provider routines::bad decrypt'
[004]  ...
[004]  ciph.decrypt(enc, pass, bad_iv)
[004]  ---
[004] -- error: 'OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad
[004] -    decrypt'
[004] +- error: 'OpenSSL error: error:1C800064:Provider routines::bad decrypt'
[004]  ...
[004]  test_run:cmd("clear filter")
[004]  ---

```

or

```
[011]  digest.pbkdf2_hex("password", "salt")
[011]  ---
[011] -- 0394a2ede332c9a13eb82e9b24631604c31df978b4e2f0fbd2c549944f9d79a536ceea9b92c6170cbbf0153ef33a4ff57321e17b7a5fadc33f7023ddd325da4744753b6d61571dcba34ae96099068cea39a07a4303263cf3749b5fbc93222946a3987f75f2d6aeea024acc4f95a0d6e7141cdb0b1f12065030ac169507f91b32
[011] +- '5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555'
[011]  ...
[011]  s, err = pcall(digest.pbkdf2, 12, "salt")
[011]  ---
[011] @@ 
```

So, we need to stay with openssl@1.1 until we haven't upgraded all tests and fix deprecation warnings.

**Review by Totktonada — APPROVED** [review]
Okay, it seems, we actully need to work it around.

**Review by kyukhin — APPROVED** [review]
