### ISSUE TITLE
Fails to build on OS X 10.14 from homebrew

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3819]
Tarantool version: 1.10

OS version: OS X 10.14

Bug description:

Fails to build from homebrew on OS X 10.14

Steps to reproduce:

brew install --HEAD tarantool

Logs:

```sh
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang  -O2 -Wall -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE  -fno-stack-protector  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -Wno-parentheses-equality -Wno-tautological-compare -Wno-misleading-indentation -Wno-varargs -Wno-implicit-fallthrough -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -c -o lj_vmmath.o lj_vmmath.c
Undefined symbols for architecture x86_64:
  "_slab_arena_create", referenced from:
      _main in arena_mt.c.o
  "_slab_arena_destroy", referenced from:
      _main in arena_mt.c.o
  "_slab_map", referenced from:
      _run in arena_mt.c.o
  "_slab_unmap", referenced from:
      _run in arena_mt.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/lib/small/test/arena_mt.test] Error 1
make[1]: *** [src/lib/small/test/CMakeFiles/arena_mt.test.dir/all] Error 2
```

**Comment by knazarov** [comment]
Answering my own question:

This is because luajit's build scripts prefer most of the compiler parts from OS X SDK, but some (namely, `ar` utility) from the regular system paths (if if finds them there). 

In my case, I had gnu binutils installed from homebrew, and looks like `ar` from there is incompatible with OS X SDK.

I don't think it's much of a bug in tarantool itself. I've removed gnu binutils and it build find.

**Comment by RunsFor** [comment]
For those who does not read comments without snippets:

```sh
brew remove binutils
```
