### ISSUE TITLE
Unable to build with glibc-2.34

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#6686]
2.10.0-beta1-317-gc9787d572

> cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF -DENABLE_FEEDBACK_DAEMON=OFF && make -j

```c
[ 81%] Building CXX object test/unit/CMakeFiles/guard.test.dir/guard.cc.o
In file included from /usr/include/signal.h:328,
                 from /home/alex/p/tarantool-meta/r/t-5/third_party/libev/ev.h:167,
                 from /home/alex/p/tarantool-meta/r/t-5/third_party/tarantool_ev.h:54,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/core/say.h:39,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/core/diag.h:41,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/core/exception.h:38,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/small/include/small/region.h:277,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/core/memory.h:33,
                 from /home/alex/p/tarantool-meta/r/t-5/test/unit/guard.cc:1:
/home/alex/p/tarantool-meta/r/t-5/test/unit/guard.cc:31:23: error: size of array ‘stack_buf’ is not an integral constant-expression
   31 | static char stack_buf[SIGSTKSZ];
      |                       ^~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-gnu-alignof-expression’ may have been intended to silence earlier diagnostics
```

**Comment by Totktonada** [comment]
If you're interested I'm going to workaround it in Gentoo's ebuild with the following patch:

```diff
diff --git a/test/unit/guard.cc b/test/unit/guard.cc
index a2953b829..4762d5611 100644
--- a/test/unit/guard.cc
+++ b/test/unit/guard.cc
@@ -28,13 +28,11 @@ stack_break_f(char *ptr)
 	return sum;
 }
 
-static char stack_buf[SIGSTKSZ];
-
 static int
 main_f(va_list ap)
 {
 	stack_t stack;
-	stack.ss_sp = stack_buf;
+	stack.ss_sp = malloc(SIGSTKSZ);
 	stack.ss_size = SIGSTKSZ;
 	stack.ss_flags = 0;
 	sigaltstack(&stack, NULL);
```
