### PR TITLE
build: fix build with glibc-2.34

### LINKED ISSUE #6686: Unable to build with glibc-2.34
2.10.0-beta1-317-gc9787d572

> cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF -DENABLE_FEEDBACK_DAEMON=OFF && make -j

```c
[ 81%] Building CXX object test/unit/CMakeFiles/guard.test.dir/guard.cc.o
In file included from /usr/include/signal.h:328,
                 from /home/alex/p/tarantool-meta/r/t-5/third_party/libev/ev.h:167,
                 from /home/alex/p/tarantool-meta/r/t-5/third_party/tarantool_ev.h:54,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/core/say.h:39,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/core/diag.h:41,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/core/exception.h:38,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/small/include/small/region.h:277,
                 from /home/alex/p/tarantool-meta/r/t-5/src/lib/core/memory.h:33,
                 from /home/alex/p/tarantool-meta/r/t-5/test/unit/guard.cc:1:
/home/alex/p/tarantool-meta/r/t-5/test/unit/guard.cc:31:23: error: size of array ‘stack_buf’ is not an integral constant-expression
   31 | static char stack_buf[SIGSTKSZ];
      |                       ^~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-gnu-alignof-expression’ may have been intended to silence earlier diagnostics
```

### PR DESCRIPTION
**Pull request by drewdzzz**
Macros SIGSTKSZ used to be an integral constant but
in glibc-2.34 it turned into a runtime function so it
cannot be used as constant known size for arrays anymore.

Beyond this, SIGSTKSZ is not enough for alt. signal stack size
when you use ASAN, so the size was increased.

Closes #6686

### CODE REVIEW

File: changelogs/unreleased/gh-6686-build-with-glibc-2-34.md [hunk 1]
```diff
@@ -0,0 +1,3 @@
+## bugfix/build
+
+ * Fix build errors with glibc-2.34.
```
Comment (Totktonada) [inline changelogs/unreleased/gh-6686-build-with-glibc-2-34.md:3]: Nit: Extra whitespace at beginning of the line.

File: test/unit/guard.cc [hunk 2]
```diff
@@ -28,15 +28,17 @@ stack_break_f(char *ptr)
...
-
 static int
 main_f(va_list ap)
 {
 	stack_t stack;
-	stack.ss_sp = stack_buf;
-	stack.ss_size = SIGSTKSZ;
 	stack.ss_flags = 0;
+	stack.ss_size = SIGSTKSZ;
+	stack.ss_sp = malloc(stack.ss_size);
```
Comment (locker) [inline test/unit/guard.cc:37]: Nit: please use `xmalloc` and drop the check for NULL.

**Review by Totktonada — APPROVED** [review]
No objections from me.

File: changelogs/unreleased/gh-6686-build-with-glibc-2-34.md (hunk 1 above)
Comment (locker) [inline changelogs/unreleased/gh-6686-build-with-glibc-2-34.md:3]: Nit: please append `(gh-6686)` to the message, like we usually do. Also, please link the PR and commit to the issue by adding `Closes #6686` to the commit message / PR description.

**Review by locker — CHANGES_REQUESTED** [review]

File: test/unit/guard.cc (hunk 2 above)
Comment (locker) [reply test/unit/guard.cc:37]: This comment is still unresolved. Did you miss it or is there anything wrong with xmalloc that prevents it from being used here? Overall, we are shifting towards xmalloc throughout the code base, see #3534.

Also, please don't resolve comments by yourself. Instead reply to a comment and let the reviewer resolve it, otherwise it's difficult for the reviewer to figure out what you did. If you fully agree, it suffices to reply with something like "Fixed."

Comment (drewdzzz) [reply test/unit/guard.cc:37]: > Did you miss it or is there anything wrong with xmalloc that prevents it from being used here?

Manual check for NULL lets me write that the allocation failed to reject file. So if allocations fails reject file contains message "cannot allocate memory for alt signal stack" while it will fail without any message if I use xmalloc. As for me, the first variant is better.

Comment (drewdzzz) [reply test/unit/guard.cc]: Changed to xmalloc.

**Review by locker — APPROVED** [review]

**Review by locker — APPROVED** [review]

**Comment by Totktonada** [comment]
Please, backport to 1.10 and 2.8 as well.

**Comment by locker** [comment]
> Please, backport to 1.10 and 2.8 as well.

Done.
