### ISSUE TITLE
build: `-Werror,-Wvla-cxx-extension` fails the build on Clang 18

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10354]
Tarantool: 3.2.0-entrypoint-204-g09bfdd473f
OS: Linux

I'm trying to compile a debug build that assumes `-Werror`. It works on Clang 17.0.6, but doesn't work on Clang 18.1.3.

```shell
$ CC=clang-17 CXX=clang++-17 cmake . -DCMAKE_BUILD_TYPE=Debug && make -j8
```

```shell
$ CC=clang-18 CXX=clang++-18 cmake . -DCMAKE_BUILD_TYPE=Debug && make -j8
```

```c
/home/alex/p/tarantool-meta/tarantool/test/unit/bps_tree.cc:33:1: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
   33 | SPTREE_DEF(test, realloc, qsort_arg);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/alex/p/tarantool-meta/tarantool/third_party/sptree.h:357:23: note: expanded from macro 'SPTREE_DEF'
  357 |     spnode_t    path[ t->max_depth + 2];                                                  \
      |                       ^~~~~~~~~~~~~~~~
/home/alex/p/tarantool-meta/tarantool/test/unit/bps_tree.cc:33:1: note: function parameter 't' with unknown value cannot be used in a constant expression
/home/alex/p/tarantool-meta/tarantool/third_party/sptree.h:357:23: note: expanded from macro 'SPTREE_DEF'
  357 |     spnode_t    path[ t->max_depth + 2];                                                  \
      |                       ^
/home/alex/p/tarantool-meta/tarantool/test/unit/bps_tree.cc:33:1: note: declared here
/home/alex/p/tarantool-meta/tarantool/third_party/sptree.h:355:40: note: expanded from macro 'SPTREE_DEF'
  355 | sptree_##name##_replace(sptree_##name *t, void *v, void **p_old) {                        \
      |                                        ^
```

Tarantool executable itself compiles fine, but `test/unit/bps_tree.cc` fails to compile.
