### ISSUE TITLE
Tarantool failed to build in clang 3.7.0

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1295]
```
# head -n 4 /etc/os-release 
NAME=Fedora
VERSION="24 (Rawhide)"
ID=fedora
VERSION_ID=24

# clang --version
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-redhat-linux-gnu
Thread model: posix

....
-- VERSION: 1.6.8-390-ge15bc62
-- BUILD: Linux-x86_64-Debug
-- C_COMPILER: /usr/lib64/ccache/clang
-- CXX_COMPILER: /usr/lib64/ccache/clang++
-- C_FLAGS: -fno-common -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Werror
-- CXX_FLAGS: -fno-common -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Werror

```

```
[ 21%] Linking CXX executable bps_tree_itr.test
/home/buildslave/tarantool/test/unit/unit.c:54:279: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
  { int res = _ok((r) == (0), "subtests"); if (!res) { _space(stderr); fprintf(stderr, "#   Failed test '"); fprintf(stderr, "subtests"); fprintf(stderr, "'\n"); _space(stderr); fprintf(stderr, "#   in %s at line %d\n", "/home/buildslave/tarantool/test/unit/unit.c", 54); } res = res; };
                                                                                                                                                                                                                                                                                  ~~~ ^ ~~~
1 error generated.

In file included from /home/buildslave/tarantool/src/cbus.c:31:
/home/buildslave/tarantool/src/cbus.h:389:433: error: expression result unused [-Werror,-Wunused-value]
 ({ int e = pthread_mutex_lock(&bus->mutex); ({ _say(S_DEBUG, "/home/buildslave/tarantool/src/cbus.h", 389, ((void*)0), "%s: locking %s", __func__, "&bus->mutex"); }); if (e != 0) ({ _say(S_SYSERROR, "/home/buildslave/tarantool/src/cbus.h", 389, strerror((*__errno_location ())), "%s error %d", __func__, e); }); ((e == 0) ? (void) (0) : __assert_fail ("e == 0", "/home/buildslave/tarantool/src/cbus.h", 389, __PRETTY_FUNCTION__)); e;});
                                                                                                                                                                                                                                                                                                                                                                                                                                                ^
/home/buildslave/tarantool/src/cbus.h:396:437: error: expression result unused [-Werror,-Wunused-value]
 ({ int e = pthread_mutex_unlock(&bus->mutex); ({ _say(S_DEBUG, "/home/buildslave/tarantool/src/cbus.h", 396, ((void*)0), "%s: unlocking %s", __func__, "&bus->mutex"); }); if (e != 0) ({ _say(S_SYSERROR, "/home/buildslave/tarantool/src/cbus.h", 396, strerror((*__errno_location ())), "%s error %d", __func__, e); }); ((e == 0) ? (void) (0) : __assert_fail ("e == 0", "/home/buildslave/tarantool/src/cbus.h", 396, __PRETTY_FUNCTION__)); e; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ^
/home/buildslave/tarantool/src/cbus.h:402:310: error: expression result unused [-Werror,-Wunused-value]
 ({ int e = pthread_cond_signal(&bus->cond); if (e != 0) ({ _say(S_SYSERROR, "/home/buildslave/tarantool/src/cbus.h", 402, strerror((*__errno_location ())), "%s error %d", __func__, e); }); ((e == 0) ? (void) (0) : __assert_fail ("e == 0", "/home/buildslave/tarantool/src/cbus.h", 402, __PRETTY_FUNCTION__)); e; });

/home/buildslave/tarantool/src/box/xlog.cc:444:311: error: expression result unused [-Werror,-Wunused-value]
  ({ ({ _say(S_DEBUG, "/home/buildslave/tarantool/src/box/xlog.cc", 444, __null, "%s at %s:%i", "OutOfMemory", "/home/buildslave/tarantool/src/box/xlog.cc", 444); }); OutOfMemory *e = new OutOfMemory("/home/buildslave/tarantool/src/box/xlog.cc", 444, len, "region", "new slab"); diag_add_error(diag_get(), e); e; });
                                                                                                                                                                                                                                                                                                                      ^
/home/buildslave/tarantool/src/box/xlog.cc:460:309: error: expression result unused [-Werror,-Wunused-value]
  ({ ({ _say(S_DEBUG, "/home/buildslave/tarantool/src/box/xlog.cc", 460, __null, "%s at %s:%i", "ClientError", "/home/buildslave/tarantool/src/box/xlog.cc", 460); }); ClientError *e = new ClientError("/home/buildslave/tarantool/src/box/xlog.cc", 460, ER_INVALID_MSGPACK, buf); diag_add_error(diag_get(), e); e; });

lj_gc.c:206:21: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
  if (((fn)->c.ffid == 0)) {
       ~~~~~~~~~~~~~^~~~
lj_gc.c:206:21: note: remove extraneous parentheses around the comparison to silence this warning
  if (((fn)->c.ffid == 0)) {
      ~             ^   ~
lj_gc.c:206:21: note: use '=' to turn this equality comparison into an assignment
  if (((fn)->c.ffid == 0)) {
                    ^~
                    =
lj_gc.c:274:23: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    if (((fn)->c.ffid == 0)) ftop += (((((fn)->c.ffid == 0)) ? (void) (0) : __assert_fail ("((fn)->c.ffid == 0)", "lj_gc.c", 274, __PRETTY_FUNCTION__)), ((GCproto *)(((char *)(void *)(uintptr_t)((fn)->l.pc).ptr32)-sizeof(GCproto))))->framesize;
         ~~~~~~~~~~~~~^~~~
lj_gc.c:274:23: note: remove extraneous parentheses around the comparison to silence this warning
    if (((fn)->c.ffid == 0)) ftop += (((((fn)->c.ffid == 0)) ? (void) (0) : __assert_fail ("((fn)->c.ffid == 0)", "lj_gc.c", 274, __PRETTY_FUNCTION__)), ((GCproto *)(((char *)(void *)(uintptr_t)((fn)->l.pc).ptr32)-sizeof(GCproto))))->framesize;
        ~             ^   ~

lj_meta.c:288:17: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
 if ((((o)->it) == (~4u))) {
      ~~~~~~~~~~^~~~~~~~
lj_meta.c:288:17: note: remove extraneous parentheses around the comparison to silence this warning
 if ((((o)->it) == (~4u))) {
     ~          ^       ~
lj_meta.c:288:17: note: use '=' to turn this equality comparison into an assignment
 if ((((o)->it) == (~4u))) {
                ^~
                =
2 warnings generated.
CC        lj_api.o
CC        lj_profile.o

lj_err.c:574:79: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
  if (((((&((GCobj *)(uintptr_t)((L->base-1)->fr.func).gcptr32)->fn))->c.ffid == 0))) L->top = (L->base + (((((((&((GCobj *)(uintptr_t)(
(L->base-1)->fr.func).gcptr32)->fn))->c.ffid == 0)) ? (void) (0) : __assert_fail ("(((&((GCobj *)(uintptr_t)((L->base-1)->fr.func).gcptr
32)->fn))->c.ffid == 0)", "lj_err.c", 574, __PRETTY_FUNCTION__)), ((GCproto *)(((char *)(void *)(uintptr_t)(((&((GCobj *)(uintptr_t)((L-
>base-1)->fr.func).gcptr32)->fn))->l.pc).ptr32)-sizeof(GCproto)))))->framesize);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/buildslave/tarantool/src/fiber.c:730:323: error: expression result unused [-Werror,-Wunused-value]
 ({ int e = pthread_mutex_destroy(&ct_arg.start_mutex); if (e != 0) ({ _say(S_SYSERROR, "/home/buildslave/tarantool/src/fiber.c", 730, strerror((*__errno_location ())), "%s error %d", __func__, e); }); ((e == 0) ? (void) (0) : __assert_fail ("e == 0", "/home/buildslave/tarantool/src/fiber.c", 730, __PRETTY_FUNCTION__)); e; });
                                                                                                                                                                                                                                                                                                                                  ^
/home/buildslave/tarantool/src/fiber.c:731:321: error: expression result unused [-Werror,-Wunused-value]
 ({ int e = pthread_cond_destroy(&ct_arg.start_cond); if (e != 0) ({ _say(S_SYSERROR, "/home/buildslave/tarantool/src/fiber.c", 731, strerror((*__errno_location ())), "%s error %d", __func__, e); }); ((e == 0) ? (void) (0) : __assert_fail ("e == 0", "/home/buildslave/tarantool/src/fiber.c", 731, __PRETTY_FUNCTION__)); e; });

```

It seems that clang has significant regressions in C preprocessor.

**Comment by rtsisyk** [comment]
3.7.0 is now OK.
See also #1626
