### ISSUE TITLE
build: Failed to build Tarantool on MacOS with -DENABLE_BUNDLED_ZSTD=OFF

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#6162]
Failed to build Tarantool 2.9.0-101-gc7f8fe0b2 on MacOS BigSur 11.4 with -DENABLE_BUNDLED_ZSTD=OFF

```
cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF -DENABLE_BUNDLED_ZSTD=OFF -DZSTD_INCLUDE_DIR=/usr/local/opt/zstd/include && make -j
...
Consolidate compiler generated dependencies of target box
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.c:31:
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.h:44:
/Users/o.babin/Projects/tarantool/src/box/xlog.h:40:10: fatal error: 'zstd.h' file not found
#include "zstd.h"
         ^~~~~~~~
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.c:31:
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.h:44:
/Users/o.babin/Projects/tarantool/src/box/xlog.h:40:10: fatal error: 'zstd.h' file not found
#include "zstd.h"
         ^~~~~~~~
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_range.c:49:
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.h:44:
/Users/o.babin/Projects/tarantool/src/box/xlog.h:40:10: fatal error: 'zstd.h' file not found
#include "zstd.h"
         ^~~~~~~~
1 error generated.
make[2]: *** [test/unit/CMakeFiles/vy_point_lookup.test.dir/__/__/src/box/vy_range.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_write_iterator.c:33:
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.h:44:
/Users/o.babin/Projects/tarantool/src/box/xlog.h:40:10: fatal error: 'zstd.h' file not found
#include "zstd.h"
         ^~~~~~~~
1 error generated.
1 error generated.
make[2]: *** [test/unit/CMakeFiles/vy_write_iterator.test.dir/__/__/src/box/vy_run.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [test/unit/CMakeFiles/vy_point_lookup.test.dir/__/__/src/box/vy_run.c.o] Error 1
[ 79%] Linking CXX executable xrow.test
1 error generated.
make[2]: *** [test/unit/CMakeFiles/vy_write_iterator.test.dir/__/__/src/box/vy_write_iterator.c.o] Error 1
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_write_iterator.c:33:
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.h:44:
/Users/o.babin/Projects/tarantool/src/box/xlog.h:40:10: fatal error: 'zstd.h' file not found
#include "zstd.h"
         ^~~~~~~~
1 error generated.
make[2]: *** [test/unit/CMakeFiles/vy_point_lookup.test.dir/__/__/src/box/vy_write_iterator.c.o] Error 1
[ 79%] Built target xrow.test
In file included from /Users/o.babin/Projects/tarantool/test/unit/vy_point_lookup.c:5:
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.h:44:
/Users/o.babin/Projects/tarantool/src/box/xlog.h:40:10: fatal error: 'zstd.h' file not found
#include "zstd.h"
         ^~~~~~~~
1 error generated.
make[2]: *** [test/unit/CMakeFiles/vy_point_lookup.test.dir/vy_point_lookup.c.o] Error 1
[ 79%] Linking CXX executable vy_mem.test
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_point_lookup.c:46:
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.h:44:
/Users/o.babin/Projects/tarantool/src/box/xlog.h:40:10: fatal error: 'zstd.h' file not found
#include "zstd.h"
         ^~~~~~~~
1 error generated.
make[1]: *** [test/unit/CMakeFiles/vy_write_iterator.test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [test/unit/CMakeFiles/vy_point_lookup.test.dir/__/__/src/box/vy_point_lookup.c.o] Error 1
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_lsm.c:52:
In file included from /Users/o.babin/Projects/tarantool/src/box/vy_run.h:44:
/Users/o.babin/Projects/tarantool/src/box/xlog.h:40:10: fatal error: 'zstd.h' file not found
#include "zstd.h"
         ^~~~~~~~
[ 79%] Linking CXX executable vy_cache.test
...
```

**Comment by olegrok** [comment]
This patch helps me:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5e4e630a5..2c280706f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -383,6 +383,7 @@ if (ENABLE_BUNDLED_ZSTD)
 else()
     set(ZSTD_FIND_REQUIRED ON)
     find_package(ZSTD)
+    include_directories(${ZSTD_INCLUDE_DIR})
 endif()
 
 #
```

After this patch fails because of https://github.com/tarantool/tarantool/pull/6145. And it seems to be OK if diff applied on top of https://github.com/tarantool/tarantool/pull/6145.

**Comment by Totktonada** [comment]
Verified the build on Linux (@olegrok asked me). Checked out the latest master (c7f8fe0b2c0ad7bed5626e3a06f6fe189a4ec865), applied PR #6145 patches, applied the patch above. Built with external ZSTD:

```
$ cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF -DENABLE_BUNDLED_ZSTD=OFF && make -j
```

It is successful.
