### PR TITLE
build: support cmake 4.0

### PR DESCRIPTION
**Pull request by chenrui333**
as cmake < 3.5 support has been removed in cmake 4, bump the minimum_version to 3.5

```
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 has been removed from CMake.
```

relates to https://github.com/Homebrew/homebrew-core/pull/219323

### CODE REVIEW

**Comment by Totktonada** [comment]
Updated the commit message (by checkpatch complains).

**Comment by Totktonada** [comment]
`release_lto` job gives the following error:

```c
/__w/tarantool/tarantool/test/unit/func_adapter_func.c: In function ‘main’:
/__w/tarantool/tarantool/test/unit/func_adapter_func.c:124:3: error: ‘returned_pin_type’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  124 |   is(returned_pin_type, pin_type,
      |   ^
/__w/tarantool/tarantool/test/unit/func_adapter_func.c:121:25: note: ‘returned_pin_type’ was declared here
  121 |   enum func_holder_type returned_pin_type;
      |                         ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[3]: *** [test/unit/CMakeFiles/func_adapter_func.test.dir/build.make:160: test/unit/func_adapter_func.test] Error 1
```

@drewdzzz, do you know anything about it?

**Comment by Totktonada** [comment]
@drewdzzz, @mkostoevr, also there are CI job failures in https://github.com/tarantool/tarantool-ee/commit/f5f10982e55b313025b579254e6bb5c06aa10173 -- I've pushed it to verify EE build. Could you glance on them?

**Comment by drewdzzz** [comment]
@Totktonada 
About EE failures:
```
/__w/tarantool-ee/tarantool-ee/src/box/memtx_tx_read_view.c:55:68: error: ‘struct memtx_tx_snapshot_cleaner_entry’ has no member named ‘hint’
   55 |                                               (struct tuple *)entry->hint :
```

The PR should be rebased on the newest master - it lacks recently pushed 50b8cf1153e028c9d5f776255a4ead5e8b21b678.

**Comment by drewdzzz** [comment]
@Totktonada 
About `func_adapter_func` unit test. There's nothing serious, complier just warns us that the value can be uninitialized, but that's not actually the case there. This patch should solve the problem:
```diff
diff --git a/test/unit/func_adapter_func.c b/test/unit/func_adapter_func.c
index 2e382af18a..b58f376bde 100644
--- a/test/unit/func_adapter_func.c
+++ b/test/unit/func_adapter_func.c
@@ -118,7 +118,7 @@ test_func_adapter_func_is_pinned(void)
 			func_adapter_func_create(func, pin_type);
 		fail_if(func_adapter == NULL);
 
-		enum func_holder_type returned_pin_type;
+		enum func_holder_type returned_pin_type = FUNC_HOLDER_MAX;
 		ok(func_is_pinned(func, &returned_pin_type),
 		   "Underlying func must be pinned");
 		is(returned_pin_type, pin_type,
```

**Comment by Totktonada** [comment]
@drewdzzz, I met this build failure locally on `master` without any patches, so I sent the patch separately in #11405.

**Comment by Totktonada** [comment]
Rebased after PR #11405. Seems successful.

[CI](https://github.com/tarantool/tarantool-ee/commit/0b686796e09b7391d9faf40a1e286cc3828d75a9) for EE (w/o changing `cmake_minimum_required` on the EE side -- just to verify that nothing will break after the CE submodule bump). Seems successful.

Should I verify anything else before proceed? @ligurio, @sergos?

**Review by Totktonada — APPROVED** [review]

**Review by ligurio — APPROVED** [review]
@Totktonada Alexander, thanks for your work! I have no objections.
